version: '3'

services:
  metabase:
    image: metabase/metabase
    container_name: metabase
    environment:
      - MB_DB_TYPE=pooooooo
      - MB_DB_DBNAME=metabaseappdb
      - MB_DB_PORT=5432
      - MB_DB_USER=name
      - MB_DB_PASS=password
      - MB_DB_HOST=my-database-host
    ports:
      - 3000:3000
    networks:
      - metabase-net

networks:
  metabase-net:
    name: metabase-net
    
